parameters:
    tms_faq_client.manager.faq.class: Tms\Bundle\FaqClientBundle\Manager\FaqManager
    tms_faq_client.manager.evaluation.class: Tms\Bundle\FaqClientBundle\Manager\EvaluationManager

services:
    tms_faq_client.manager.faq:
        class: %tms_faq_client.manager.faq.class%
        arguments: [ @da_api_client.api.faq, @tms_faq_client.parser.faq ]

    tms_faq_client.manager.evaluation:
        class: %tms_faq_client.manager.evaluation.class%
        arguments: [ @da_api_client.api.faq, @tms_faq_client.parser.evaluation ]
