parameters:
    tms_faq_client.parser.faq.class: Tms\Bundle\FaqClientBundle\Parser\FaqParser
    tms_faq_client.parser.questionCategory.class: Tms\Bundle\FaqClientBundle\Parser\QuestionCategoryParser
    tms_faq_client.parser.question.class: Tms\Bundle\FaqClientBundle\Parser\QuestionParser
    tms_faq_client.parser.response.class: Tms\Bundle\FaqClientBundle\Parser\ResponseParser

services:
    tms_faq_client.parser.faq:
        class: %tms_faq_client.parser.faq.class%
        arguments: [ @tms_faq_client.parser.questionCategory]

    tms_faq_client.parser.questionCategory:
        class: %tms_faq_client.parser.questionCategory.class%
        arguments: [ @tms_faq_client.parser.question]

    tms_faq_client.parser.question:
        class: %tms_faq_client.parser.question.class%
        arguments: [ @tms_faq_client.parser.response]

    tms_faq_client.parser.response:
        class: %tms_faq_client.parser.response.class%
